### PR TITLE
PHP4 constructors, preg_replace, method naming for subclasses

### PR DESCRIPTION
**Pull request by fwolfsjaeger**
I've fixed issue #28 with the second commit. The first one fixes another preg_replace delimiter issue, it's also allowed to use single-/double-quotes as delimiters. Also the method naming check didn't work for subclasses (eg. class SubClass extends ParentClass) as there were more tokens than just 5 to get after the first opening brace.

### CODE REVIEW

**Comment by fwolfsjaeger** [comment]
It's just a partial fix for #28 though as it doesn't check for the namespace. Simply checking if there's a namespace defined in the same file would be simple, but it could then skip issues for the following (crappy yet allowed) syntax:

```
namespace name\space\to1 {
	class FirstClass {
		public function FirstClass() {
			print 'first class';
		}
	}

	$firstClass = new FirstClass();
}

namespace name\space\to2 {
	class SecondClass {
		public function SecondClass() {
			print 'second class';
		}
	}

	$secondClass = new SecondClass();
}
```

**Comment by fwolfsjaeger** [comment]
Alright, namespace check for PHP4 style constructs is done as well ...

**Comment by wapmorgan** [comment]
Hello. Have you tested it?

**Comment by fwolfsjaeger** [comment]
Hi,

A couple of times with several different files, the final version works
just fine for me. It did throw some warnings after the 2nd or 3rd commit,
so please be careful in case you don't want to merge them all.

Is there any reason why you had the array_splice() for the method checks
strip from $class_start until $i - $class_start instead of 0 to $i?

BR,
Flo

**Comment by wapmorgan** [comment]
> Is there any reason why you had the array_splice() for the method checks
strip from $class_start until $i - $class_start instead of 0 to $i?
That's to remove only tokens within `class { ... }` and to preserve `use`'s and similar.

**Comment by wapmorgan** [comment]
Thanks for pr!

**Comment by fwolfsjaeger** [comment]
Hi,

Your tool really helped us with migrating to PHP 7.2, so I'm glad I could
help at least a bit in return.

BR,
Flo

**Pull request merged**
